### ISSUE TITLE
Can't link Material library

### ISSUE THREAD

**Issue by lexuanquynh** [CosmicMind/Samples#105]
I use  ./install_all_pods.sh and get error:
![screen shot 2018-01-10 at 2 17 51 pm](https://user-images.githubusercontent.com/17588791/34760121-1223e710-f611-11e7-9039-61ae17817df2.png)
what is wrong?
  I'm try open single project and I get error:
![screen shot 2018-01-10 at 2 24 30 pm](https://user-images.githubusercontent.com/17588791/34760344-17ab4006-f612-11e7-8f2c-c2e664d98a5e.png)

**Comment by daniel-jonathan** [comment]
Hey! You are installing pods and using the main Samples workspace. You can only use the main sample workspace if you use the embedded installation option. Otherwise, you need to open the workspace for each sample that has the installed pods. If you need, please review this [installation guide](https://www.cosmicmind.com/danieldahan/lesson/6). As well, if you have any further questions on this, please reopen the issue. Thank you!
