### ISSUE TITLE
motionNavigationTransitionType = .autoReverse(presenting: .zoom) not behaving as the sample gif in the Photos App

### ISSUE THREAD

**Issue by mariusgab** [CosmicMind/Samples#107]
So when tapping a photo the sample gif shows the zoom in transition, but when running the project on simulator and tapping on the photo it actually has the standard iOS push transition.

**Comment by daniel-jonathan** [comment]
Hey! I updated the project to behave correctly. I will need to make an adjustment for the bottom TabBar when using iPhone X. Otherwise, update your local copy of the repo and all will work correctly. Before, Motion was enabled by default when using the NavigationController. Now it needs to enabled by default. All the best!

**Comment by mariusgab** [comment]
Thank you!
