### ISSUE TITLE
Help with MenuController

### ISSUE THREAD

**Issue by codemodouk** [CosmicMind/Samples#22]
Hi Daniel,

Firstly, I love Material, I'm really enjoying using it in my project. I'm new to iOS and Swift, so Material is a great kickstart to getting me up and running.

I have a requirement where I want to use the MenuController in a single View Controller in the app, as the menu items are specific to that view controller. The example shows how it is used as a application wide MenuController. 

Currently, similar to the example, I have a SearchMenuViewController which is equivalent to the example AppMenuViewController, and I have a SearchMenuItemsViewController which is the equivalent to the example RootViewController. In my parent view controller, I have a property for my SearchMenuViewController which I instantiate in the same way as the example - 

`searchMenuVC = SearchMenuViewController(rootViewController: SearchMenuItemsViewController())`

When I debug the app, I see the trace drops into ViewDidLoad on the SearchMenuItemsViewController, but never drops into ViewDidAppear, so the prepareMenuController function never gets called, and thus doesn't add the menu item subviews and set the delegate. If I move the prepareMenuController call to happen in ViewDidLoad, I can see the menu item fab button in my parent VC, but it doesn't respond to taps.

Do you have an example that I can follow for using the MenuController in a single parent view controller, or can you give me any pointers where I might be going wrong?

Thanks
Alex

**Comment by daniel-jonathan** [comment]
Hey, I am happy that you are enjoying Material :) Thank you. 

Yes, I can help. A little explanation of how to think of the navigation controllers in general (ToolbarController, MenuController, NavigationDrawerController, etc...) should help you. 

The main idea is to provide flexibility in architecting your application. The first concept to understand is the layering system for navigation controls. You can layer the order in which you stack the navigation controllers, so that you can control your application's flow more easily. With the layering system, accessing the parent navigation controls is done through the optional helper accessor properties, such as: `menuController?...`, `navigationDrawerController?...`, etc... 

So now that we have a layering system, we can decide to populate the navigation controllers, MenuController in your case, in different subview controllers. You have the choice of adding the MenuController at a high level, application wide, and then only revealing it and adding buttons from a view controller that appears within the hierarchy, for example `SearchMenuItemsViewController`. 

Things to consider, that you cannot access the helper optional accessory properties for navigation controllers in the `viewDidLoad` method when you create the object and then add it as the `rootViewController`, like so:

``` swift
searchMenuVC = SearchMenuViewController(rootViewController: SearchMenuItemsViewController())
```

The reason being is that the relationship, parent-child, is not yet established resulting in a `nil` value when using the helper accessory properties. So you need to access it in the `viewWillAppear`, or `viewDidAppear` method. 

Setting the delegate can always change when you are introducing new view controllers, allowing you to reuse the same application wide navigation controller, which would require some planning to ensure you don't try and double bind a delegation object, much easier to do than it may sound. 

Lack in response to clicking buttons is when you have set the handlers in a view controller that is then removed from the view hierarchy, so the handlers are no longer available. In this case, you would probably want to place the handlers in an object, or view controller that is always `alive`, such as a subclass of the navigation controller type itself, like `AppMenuController`. 

Also please update to [Material 2.3.12](https://github.com/CosmicMind/Material/releases) as I pushed updates specifically for the `MenuController` and animations in iOS 8, 9, and 10. 

Any questions so far?

**Comment by codemodouk** [comment]
Hi Daniel,

Thanks for the quick and detailed response.

I think I understand from your explanation that the menuController property is available across sub view controllers to be used as required by those sub VCs.

What I don't understand, is where you would create it in a Storyboard based app. Sorry if I didn't make this clear in my initial post. My Storyboard setup uses a `uitabbarcontroller` as the initial view controller. One of the controllers on the tab bar controller needs to access and use the menuController property. 

In the the sample app the MenuController sub class is instantiated in the app delegate, and made the rootViewController for the window. In my case, the rootViewController for the window is defined in the storyboard. So where do I instantiate my MenuController subclass?

I feel I'm missing something very obvious, so, I apologise if this sounds a bit basic. If I can assist further to help clarify my situation more please let me know.

Thanks again
Alex

**Comment by codemodouk** [comment]
Hi Daniel,

A nights sleep makes everything much clearer! I've got my head around this now, and I'm able to move on. Please feel free to close the issue.

Thank you for your support.

Regards
Alex

**Comment by daniel-jonathan** [comment]
Awesome :) Feel free to reach out anytime, we are here to help.
