### ISSUE TITLE
Disable NavigationDrawer in Pushed ViewController

### ISSUE THREAD

**Issue by tarek903** [CosmicMind/Samples#28]
Hi, i just have a question

i have a RootViewController (MainViewController With navidrawer and Menu Button(FAB))

```
let MainViewController: MainViewController = {
            return UIStoryboard.viewController(identifier: "MainViewController") as! MainViewController
        }()
        
        let NaviLeftViewController: NaviLeftViewController = {
            return UIStoryboard.viewController(identifier: "NaviLeftViewController") as! NaviLeftViewController
        }()
        
        let ApptoolBar =  AppNavigationController(rootViewController: MainViewController)
        
        let NaviDrawer =  AppNavigationDrawerController(rootViewController: ApptoolBar, leftViewController: NaviLeftViewController, rightViewController: nil)
        
        
        
        let SnackBar   =    AppSnackbarController(rootViewController: NaviDrawer)
        
        let Menu       = AppMenuController(rootViewController: SnackBar)
        
        
        UIApplication.shared.keyWindow?.rootViewController = Menu
```

when i push using the navigation controller the naviDrawer and the menu are shown in the Pushed View Controller

`self.navigationController?.pushViewController(OrderBidsView, animated: true)`

i can hide them and show in both viewControllers , but is there a way to hide the navidrawer and the menu in pushed view controllers instead of showing and hiding them manually?

**Comment by daniel-jonathan** [comment]
Hey :)

They are showing because you put them as the outermost view controller. When you do that, they will always be there ready for use, but you don't need to use them until necessary. It is actually better, because you can reuse the controllers, also you can use them as points to put code that is completely relevant to them. The other option is to use them as your sub controllers. Then you will need to create a new one for every view controller that needs it. This is also good when you need that type of organization. Their design is meant to be used in anyway that is correct for your needs and maintenance. I am working on an article for it: http://cosmicmind.com/danieldahan/application-architecture-with-material, so feel free to follow that over the next couple days, as I will be covering all of this :) 

Please reopen or create a new issue if needed.

**Comment by tariq235** [comment]
@danieldahan  @tarek903 Can you please guys take a look into this. This is something very urgent https://github.com/CosmicMind/Material/issues/733
